version: '3'
services:
  blue-dev:
    image: photique/backend-blue-dev:0.1.0
    container_name: blue-dev
    volumes:
      - /home/ubuntu/spring:/spring
    ports:
      - "8081:8080"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    user: root


  green-dev:
    image: photique/backend-green-dev:0.1.0
    container_name: green-dev
    volumes:
      - /home/ubuntu/spring:/spring
    ports:
      - "8082:8080"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    user: root

networks:
  backend:
    external: true
