version: '3'
services:
  blue-prod:
    image: photique/backend-blue-prod:0.1.0
    container_name: blue-prod
    volumes:
      - /home/photique0538/spring:/spring
    ports:
      - "8081:8080"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    user: root


  green-prod:
    image: photique/backend-green-prod:0.1.0
    container_name: green-prod
    volumes:
      - /home/photique0538/spring:/spring
    ports:
      - "8082:8080"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    user: root

networks:
  backend:
    external: true
