name: 프로덕트 서버 Spring App 배포

on:
  pull_request:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"

      - name: 앱 빌드
        run: ./gradlew clean build -x test

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_REPO_BLUE_PROD }}:0.1.0 .
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_REPO_GREEN_PROD }}:0.1.0 .
          docker push ${{ secrets.DOCKER_REPO_BLUE_PROD }}:0.1.0
          docker push ${{ secrets.DOCKER_REPO_GREEN_PROD }}:0.1.0

      - name: EC2에 파일 복사
        uses: appleboy/scp-action@master
        with:
          username: photique0538
          host: ${{ secrets.HOST_PROD }}
          key: ${{ secrets.KEY_PROD }}
          script: mkdir -p /home/photique0538/spring
          source: docker/docker-compose.backend.prod.yml, deployment/deploy-prod.sh, deployment/rollback-prod.sh
          target: /home/photique0538/spring

      - name: EC2 연결 및 backend 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          username: photique0538
          host: ${{ secrets.HOST_PROD }}
          key: ${{ secrets.KEY_PROD }}
          script: |
            mv /home/photique0538/spring/docker/docker-compose.backend.prod.yml /home/photique0538/spring/
            mv /home/photique0538/spring/deployment/*.sh /home/photique0538/spring/
            rm -rf /home/photique0538/spring/docker
            rm -rf /home/photique0538/spring/deployment
            echo ">>> 사용되지 않는 도커 시스템 리소스 정리"
            docker system prune -a -f
            chmod +x /home/photique0538/spring/deploy-prod.sh
            echo ">>> 배포 스크립트 실행 시작"
            bash /home/photique0538/spring/deploy-prod.sh
            echo ">>> 배포 스크립트 실행 완료"
            

